# Generated by Django 2.2.4 on 2019-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movies.Genre'),
        ),
    ]
